using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace theBrent.FitLibrary.FieldTypes
{
    public class FitField_Timezone : FitField_Enum
    {
        public new Timezone? Value
        {
            get { return (Timezone?)base.Value; }
        }

        public FitField_Timezone(byte[] fieldData) : base(fieldData) { }
    }

    public enum Timezone
    {
        almaty = 0,
        bangkok = 1,
        bombay = 2,
        brasilia = 3,
        cairo = 4,
        cape_verde_is = 5,
        darwin = 6,
        eniwetok = 7,
        fiji = 8,
        hong_kong = 9,
        islamabad = 10,
        kabul = 11,
        magadan = 12,
        mid_atlantic = 13,
        moscow = 14,
        muscat = 15,
        newfoundland = 16,
        samoa = 17,
        sydney = 18,
        tehran = 19,
        tokyo = 20,
        us_alaska = 21,
        us_atlantic = 22,
        us_central = 23,
        us_eastern = 24,
        us_hawaii = 25,
        us_mountain = 26,
        us_pacific = 27,
        other = 28,
        auckland = 29,
        kathmandu = 30,
        europe_western_wet = 31,
        europe_central_cet = 32,
        europe_eastern_eet = 33,
        jakarta = 34,
        perth = 35,
        adelaide = 36,
        brisbane = 37,
        tasmania = 38,
        iceland = 39,
        amsterdam = 40,
        athens = 41,
        barcelona = 42,
        berlin = 43,
        brussels = 44,
        budapest = 45,
        copenhagen = 46,
        dublin = 47,
        helsinki = 48,
        lisbon = 49,
        london = 50,
        madrid = 51,
        munich = 52,
        oslo = 53,
        paris = 54,
        prague = 55,
        reykjavik = 56,
        rome = 57,
        stockholm = 58,
        vienna = 59,
        warsaw = 60,
        zurich = 61,
        quebec = 62,
        ontario = 63,
        manitoba = 64,
        saskatchewan = 65,
        alberta = 66,
        british_columbia = 67,
        boise = 68,
        boston = 69,
        chicago = 70,
        dallas = 71,
        denver = 72,
        kansas_city = 73,
        las_vegas = 74,
        los_angeles = 75,
        miami = 76,
        minneapolis = 77,
        new_york = 78,
        new_orleans = 79,
        phoenix = 80,
        santa_fe = 81,
        seattle = 82,
        washington_dc = 83,
        us_arizona = 84,
        chita = 85,
        ekaterinburg = 86,
        irkutsk = 87,
        kaliningrad = 88,
        krasnoyarsk = 89,
        novosibirsk = 90,
        petropavlovsk_kamchatskiy = 91,
        samara = 92,
        vladivostok = 93,
        mexico_central = 94,
        mexico_mountain = 95,
        mexico_pacific = 96,
        cape_town = 97,
        winkhoek = 98,
        lagos = 99,
        riyahd = 100,
        venezuela = 101,
        australia_lh = 102,
        santiago = 103,
        manual = 253,
        automatic = 254,
        INVALID = 255
    }
}
